config/routes.rb
SonnysShop::Application.routes.draw do
  resources :cars

  root 'shop#home'
  get 'contact' => 'shop#contact'
  get 'services' => 'shop#services'
  get 'about' => 'shop#about'

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    upload
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload
  uploaded_io = params[:picture]
  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    file.write(uploaded_io.read)
  end
end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:vin, :year, :price, :make, :model, :engine, :transmission, :body_style, :exterior_color, :interior_color, :body_style)
    end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  
  def home  
  end
  
  def contact
  end
  
  def services
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_id
    1
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="column half">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="column half">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>
</div>
<div class="row">
  <div class="column half">
    <%= f.label :mileage %>
    <%= f.text_field :mileage %>
  </div>
  <div class="column half">
    <%= f.label :make %>
    <%= f.text_field :make %>
  </div>
</div>
<div class="row">
  <div class="column half">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>
  <div class="column half">
    <%= f.label :body_style %>
    <%= f.text_field :body_style %>
  </div>
</div>
<div class="row">
  <div class="column half">
    <%= f.label :engine %>
    <%= f.text_field :engine %>
  </div>
  <div class="column half">
    <%= f.label :transmission %>
    <%= f.text_field :transmission %>
  </div>
</div>
<div class="row">
  <div class="column half">
    <%= f.label :exterior_color %>
    <%= f.text_field :exterior_color %>
  </div>
  <div class="column half">
    <%= f.label :interior_color %>
    <%= f.text_field :interior_color %>
  </div>
</div>
<div class="row">
  <div class="column half">
    <%= f.label :vin %>
    <%= f.text_field :vin %>
  </div>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <%= file_field_tag 'picture' %>
<% end %>

app/views/cars/admin_index.html.erb
<table>
  <thead>
    <tr>
      <th>Vin</th>
      <th>Year</th>
      <th>Price</th>
      <th>Make</th>
      <th>Model</th>
      <th>Engine</th>
      <th>Transmission</th>
      <th>Body style</th>
      <th>Exterior color</th>
      <th>Interior color</th>
      <th>Body style</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.vin %></td>
        <td><%= car.year %></td>
        <td><%= car.price %></td>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.engine %></td>
        <td><%= car.transmission %></td>
        <td><%= car.body_style %></td>
        <td><%= car.exterior_color %></td>
        <td><%= car.interior_color %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Update', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/edit.html.erb
<h2>Update car</h2>

<%= render 'form' %>

<%= link_to 'Details', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<div class="car_list">
  <% @cars.each do |car| %>
  <div class="row">
    <div class="car-photo column third" >
      <img src=<%= image_url('cars/car.jpg') %> >
    </div>
    <table class="car_list_details column two-thirds">
      <h4><%= link_to (car.make + " " + car.model + " " + car.year.to_s), car %></h4>
      <tr>
        <th>Price:</th>
        <td>$<%= number_with_delimiter(car.price, :delimiter => ',') %></td>
        <th>Mileage:</th>
        <td><%= car.mileage %></td>
      </tr>
      <tr>
        <th>Type:</th>
        <td><%= car.body_style %></td>
        <th>Engine:</th>
        <td><%= car.engine %></td>
      </tr>
      <tr>
        <th>Transmission:</th>
        <td><%= car.transmission %></td>
        <th>Exterior color:</th>
        <td><%= car.exterior_color %></td>
      </tr>
      <tr>
        <th>Interior color:</th>
        <td><%= car.interior_color %></td>
      </tr>
    </table>
    <% if user_id %>
      <%= link_to 'Detail', car %> |
      <%= link_to 'Update', edit_car_path(car) %> |
      <%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<div class="car">
  <p id="notice"><%= notice %></p>
  <h3><%= @car.make + " " + @car.model + " " + @car.year.to_s %></h3>
  <div class="car-photo column half" >
    <img src=<%= image_url('cars/car.jpg') %> width=100%>
  </div>
  <table class="car_details column half">
    <tr>
      <th>Price:</th>
      <td>$<%= number_with_delimiter(@car.price, :delimiter => ',') %></td>
    </tr>
    <tr>
      <th>Year:</th>
      <td><%= @car.year %></td>
    </tr>
    <tr>
      <th>Mileage:</th>
      <td><%= @car.mileage %></td>
    </tr>
    <tr>
      <th>Make:</th>
      <td><%= @car.make %></td>
    </tr>
    <tr>
      <th>Model:</th>
      <td><%= @car.model %></td>
    </tr>
    <tr>
      <th>Type:</th>
      <td><%= @car.body_style %></td>
    </tr>
    <tr>
      <th>Engine:</th>
      <td><%= @car.engine %></td>
    </tr>
    <tr>
      <th>Transmission:</th>
      <td><%= @car.transmission %></td>
    </tr>
    <tr>
      <th>Exterior color:</th>
      <td><%= @car.exterior_color %></td>
    </tr>
    <tr>
      <th>Interior color:</th>
      <td><%= @car.interior_color %></td>
    </tr>
    <tr>
      <th>Vin:</th>
      <td><%= @car.vin %></td>
    </tr>
  </table>
  <% if user_id %>
    <%= link_to 'Update', edit_car_path(@car) %> |
    <%= link_to 'Back', cars_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sunny's Auto Shop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header-wrapper">
	<header id="header" class="container">
		<h1><a href="/" id="logo">Sunny's Auto Shop</a></h1>
		<!-- Nav -->
		<nav id="nav">
			<a href="/">Home</a>
			<a href="/about">About</a>
			<a href="/services">Services</a>
			<a href="/cars">Auto Sale</a>
			<a href="/contact">Contact</a>
		</nav>
	</header>
</div>

<!-- Content -->
<div class="content-wrapper">
	<div class="content column three-fourth">
				<%= yield %>
	</div>
	<div class="sidebar-wrapper column fourth">
		<section class="sidebar"><%= render "/shop/contact" %></section>
	</div>
</div>

<!-- Footer -->
<div id="footer-wrapper">
	<footer id="footer" class="container">
		<div class="row">
		<!-- Copyright -->
		<div id="copyright">
			&copy; Sonny's Shop. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
		</div>
	</footer>
</div>
</body>
</html>

app/views/shop/_contact.html.erb
<h3>Sunny's Shop</h3>
<p>5800 Elmwood Ave<br>Philadelphia, PA 19143</p>
<p>Phone: 215-921-6287</p>
<br />
<h3>Hours</h3>
<table class="schedule">
  <tr>
    <th>Monday</td>
    <td>9:00 - 6:00</td>
  </tr>
  <tr>
    <th>Tuesday</th>
    <td>9:00 - 6:00</td>
  </tr>
  <tr>
    <th>Wednesday</th>
    <td>9:00 - 6:00</td>
  </tr>
  <tr>
    <th>Thursday</th>
    <td>9:00 - 6:00</td>
  </tr>
  <tr>
    <th>Friday</th>
    <td>9:00 - 6:00</td>
  </tr>
  <tr>
    <th>Saturday</th>
    <td>9:00 - 6:00</td>
  </tr>
  <tr>
    <th>Sunday</th>
    <td>Closed</td>
  </tr>
</table>

app/views/shop/about.html.erb
<h2>About us</h2>
<p>Some stuffs about the shop</p>
<table class="team">
	<tr>
		<td>
			<h3>Son</h3>
			<img src="assets/team/son.jpg" width=200px>
		</td>
		<td class="teaminfo">
			Info on what he does, his experiences, and fun facts :)
		</td>
	</tr>
</table>

app/views/shop/contact.html.erb
<h2>Questions or comments?</h2>
<form method="post" action="#">
	<input name="name" placeholder="Name" type="text" class="text" />
	<input name="phone" placeholder="Phone #" type="text" class="text" />
	<input name="email" placeholder="Email" type="text" class="text" />
	Prefer method of contact:
	<select>
	  <option value="phone">Phone</option>
	  <option value="email">Email</option>
	</select>
	<textarea name="message" placeholder="Message" rows=7></textarea>
	<a class="button" href="contact" >Send Message</a>
</form>

app/views/shop/home.html.erb
<h1>Grand Opening!!!</h1>

app/views/shop/services.html.erb
<h2>Services</h2>
<ul class="check-list">
	<li>Oil</li>
	<li>Brake</li>
	<li>Tune up</li>
	<li>Tires</li>
</ul>